### PR TITLE
minor bug fix in tide

### PR DESCRIPTION
**Pull request by dalepartridge**
Fix bug during casting to complex numbers when using minor values

### CODE REVIEW

**Comment by powellb** [comment]
This is not the ideal way to create a complex array. Better would be:


ts = np.zeros(len(times))
if tide_minor:
    ts.dtype = np.complex


Normally, you don't want to do that. To be safe, you can do ts = ts.astype(np.complex, copy=False). However, for this case, we just created zeros (and there is a default conversion between 0 float and 0 complex).

**Comment by dalepartridge** [comment]
Okay, modified the pull request

**Comment by powellb** [comment]
No, you did it the slow way. I gave the code to use.

**Comment by dalepartridge** [comment]
Wasn’t sure whether you wanted it that way or the safe way, hence I went for the safe option. Updated again to use ts.dtype=np.complex

**Comment by powellb** [comment]
Looks good, accepted.

**Pull request merged**
